name: Run Tests

on:
  push:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/test.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/test.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Run tests
        run: make test
      - name: Run doc-tests
        run: make test-doc
